# Generated by Django 2.2.11 on 2020-03-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0012_auto_20200328_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsterinstance',
            name='avg_rune_efficiency',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_accuracy',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_attack',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_crit_damage',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_crit_rate',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_defense',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_hp',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_resistance',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_speed',
        ),
    ]
